
all:
	gcc -Wall xbee_client.c -o xbee_client -lxbee
	#TEST
	#gcc -Wall xbee_server.c -o xbee_server -lxbee
	#cp xbee_server ~/SDU/MDB2/sailboat-controller/bin/
	#cp shell/prepare_logline.sh ~/SDU/MDB2/sailboat-controller/bin/
