/* 
 *	SAILBOAT-CONTROLLER
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

FILE* file;
float Rate,Heading,Deviation,Variation,Yaw,Pitch,Roll,Latitude,Longitude,COG,SOG,Wind_Speed,Wind_Angle;
float Point_Start_Lat, Point_Start_Lon, Point_End_Lat, Point_End_Lon;
float Manual_Control_Rudder, Manual_Control_Sail, Rudder_Feedback;
int Navigation_System, Manual_Control;

void initfiles();
void check_system_status();
void read_manual_control_values();
void read_weather_station();
void read_rudder_feedback();


int main(int argc, char ** argv)
{
	initfiles();
	fprintf(stdout,"\nSailboat-controller running..\n");
	while (1) {
		
		check_system_status();
		read_weather_station();
		
		if (Manual_Control) 
		{
			// MANUAL CONTROL IS ON
			// Values for the RUDDER and SAIL angles are received from the User Interface.
			// Use [Manual_Control_Rudder] and [Manual_Control_Sail] files to control the actuators.
			printf("Manual control is ON\n");


		}
		else
		{

			if (Navigation_System) 
			{
			
				// here comes the control logic based on the sensor values (0 means not_set)
				printf("Manual control is OFF\n");
			

				if (Heading > 40.6)
				{
					printf("Heading [%6.3f deg] is greater than 40.6 deg\n", Heading);
				}
				else
				{
					printf("Heading [%6.3f deg] is smaller than 40.6 deg\n", Heading);
				}
			}
			else
			{
				// NAVIGATION SYSTEM IS IDLE
				// do nothing
			}

		}

		sleep(1);
	}
	return 0;
}




/*
 *	Create empty files: Manual Control, Starting Point, Ending Point
 *	Navigation system starts in IDLE mode, waiting for target point coordinates
 */
void initfiles()
{
	system("mkdir /tmp/sailboat");

	system("echo 0 > /tmp/sailboat/Navigation_System");
	system("echo 0 > /tmp/sailboat/Manual_Control");
	system("echo 0 > /tmp/sailboat/Manual_Control_Rudder");
	system("echo 0 > /tmp/sailboat/Manual_Control_Sail");
	system("echo 0 > /tmp/sailboat/Point_Start_Lat");
	system("echo 0 > /tmp/sailboat/Point_Start_Lon");
	system("echo 0 > /tmp/sailboat/Point_End_Lat");
	system("echo 0 > /tmp/sailboat/Point_End_Lon");
}


/*
 *	Check Navigation System Status
 *	[Navigation System] 
 *		- [0] Boat in IDLE status
 *		- [1] Control System ON, Rudder under control of MCU
 *	[Manual Control]
 *		- [0] OFF
 *		- [1] User takes control of the rudder position
 */
void check_system_status()
{
	file = fopen ("/tmp/sailboat/Navigation_System", "r");
	fscanf (file, "%d", &Manual_Control);
	fclose (file);
	file = fopen ("/tmp/sailboat/Manual_Control", "r");
	fscanf (file, "%d", &Manual_Control);
	fclose (file); 
}


/*
 *	Read Manual_Control values
 *	[Manual_Control_Rudder] : user value for desired RUDDER angle [-30.0 to 30.0]
 *	[Manual_Control_Sail] : user value for desired SAIL angle [ignored]
 */
void read_manual_control_values()
{
	file = fopen ("/tmp/sailboat/Manual_Control_Rudder", "r");
	fscanf (file, "%f", &Manual_Control_Rudder);
	fclose (file);
	file = fopen ("/tmp/sailboat/Manual_Control_Sail", "r");
	fscanf (file, "%f", &Manual_Control_Sail);
	fclose (file); 
}


/*
 *	Read Rudder Position Feedback
 *	This file is generated by the rudder_feedback process 
 */
void read_rudder_feedback()
{
	file = fopen ("/tmp/sailboat/Rudder_Feedback", "r");
	if(file != 0)
	{
  		fscanf (file, "%f", &Rudder_Feedback);
		fclose (file);
	}
	else
	{
		printf("ERROR: File from Rudder Feedback is missing.\n");
		exit (1);
	}
}


/*
 *	Read data from the Weather Station
 */
void read_weather_station()
{
	//RATE OF TURN
	file = fopen ("/tmp/u200/Rate", "r");
	if(file != 0)
	{
  		fscanf (file, "%f", &Rate);
		fclose (file);
	}
	else
	{
		printf("ERROR: Files from Weather Station are missing.\n");
		exit (1);
	}

	//VESSEL HEADING
	file = fopen ("/tmp/u200/Heading", "r");
  	fscanf (file, "%f", &Heading);
	fclose (file);
	file = fopen ("/tmp/u200/Deviation", "r");
  	fscanf (file, "%f", &Deviation);
	fclose (file); 
	file = fopen ("/tmp/u200/Variation", "r");
  	fscanf (file, "%f", &Variation);
	fclose (file); 

	//ATTITUDE
	file = fopen ("/tmp/u200/Yaw", "r");
  	fscanf (file, "%f", &Yaw);
	fclose (file);
	file = fopen ("/tmp/u200/Pitch", "r");
  	fscanf (file, "%f", &Pitch);
	fclose (file); 
	file = fopen ("/tmp/u200/Roll", "r");
  	fscanf (file, "%f", &Roll);
	fclose (file); 

	//GPS_DATA
	file = fopen ("/tmp/u200/Latitude", "r");
  	fscanf (file, "%f", &Latitude);
	fclose (file);
	file = fopen ("/tmp/u200/Longitude", "r");
  	fscanf (file, "%f", &Longitude);
	fclose (file);
	file = fopen ("/tmp/u200/COG", "r");
  	fscanf (file, "%f", &COG);
	fclose (file);
	file = fopen ("/tmp/u200/SOG", "r");
  	fscanf (file, "%f", &SOG);
	fclose (file);

	//WIND_DATA
	file = fopen ("/tmp/u200/Wind_Speed", "r");
  	fscanf (file, "%f", &Wind_Speed);
	fclose (file);
	file = fopen ("/tmp/u200/Wind_Angle", "r");
  	fscanf (file, "%f", &Wind_Angle);
	fclose (file);
	
}
