
all:
	### COMPILING [READ] FOR x86 ###
	gcc -Wall wsread.c -o ./bin/wsread_x86
	### COMPILING [READ] FOR ARM ###
	arm-linux-gnueabi-gcc -Wall wsread.c -o ./bin/wsread_arm

	### COMPILING [DECODE] FOR x86 ###
	gcc -Wall wsdecode.c -o ./bin/wsdecode_x86
	### COMPILING [DECODE] FOR ARM ###
	arm-linux-gnueabi-gcc -Wall wsdecode.c -o ./bin/wsdecode_arm

